# Generated by Django 5.2.12 on 2026-03-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='alerts',
        ),
    ]
