# Generated by Django 5.2.12 on 2026-03-27 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('steam', 'Steam')], max_length=10)),
                ('asset_name', models.CharField(max_length=255)),
                ('app_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=38)),
                ('price', models.DecimalField(decimal_places=2, max_digits=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='portfolio.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'asset_type', '-created_at'], name='idx_history_user_type_date')],
            },
        ),
    ]
