# Generated by Django 5.2.12 on 2026-03-27 10:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('steam', 'Steam')], max_length=10)),
                ('asset_name', models.CharField(max_length=255)),
                ('app_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=38, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('avg_buy_price', models.DecimalField(decimal_places=2, max_digits=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type', 'asset_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('app_id__isnull', False)), fields=('user', 'asset_type', 'asset_name', 'app_id'), name='unique_portfolio_with_app_id'), models.UniqueConstraint(condition=models.Q(('app_id__isnull', True)), fields=('user', 'asset_type', 'asset_name'), name='unique_portfolio_without_app_id')],
            },
        ),
    ]
